In [1]:
#import numpy
import numpy as np

#import matplotlib to plot data
import matplotlib.pyplot as plt

## Part 1: Explaining the overall purpose of the package.

##### What is numpy? 
NumPy which stands for numerical python is a Python library used for working with arrays. It was created in 2005 by Travis Oliphant as an open source project that is freely used. In python arrays are slow to process. Numpy solves this problem through something called locality. This is where arrays are stored at one continuous place in memory. Because of this numpy is up to 50 times faster than regular python.

We import numpy into the workbook as np.

In [2]:
#import numpy
import numpy as np

#I am also importing matplotlib to plot data later on.
import matplotlib.pyplot as plt

##### What is the numpy.random package?
Numpy's random module is a suite of functions based on pseudorandom number generation. To define something as random it means that it can not be predicted logically. The reason Numpy is described as pseudorandom is because there is an algorithm that generates the random number. This program could be predicted so it can not be defined as truly random.

In data science and analytics we use random numbers to test and sample. It is a good way for data analysts to fake or stimulate data. Numpy.random can generate arrays from multiple probabaility distributions as well as randlomly sample from arrays. 



In [4]:
from numpy.random import default_rng
rng = default_rng()

## Part 2: Explaining the use of the “Simple random data” and “Permutations” functions.

## Part 3: Explaining the use and purpose of at least five “Distributions” functions.

## Part 4: Explaining the use of seeds in generating pseudorandom numbers.

I briefly explained in part 1 that Numpy.random is a pseudorandom number generator. A pseudorandom number is a computer generated number that appears random, but is predetermined. 
Essentially, computers are deterministic. Meaning that if I give a computer a specific input it will return a specific output everytime. This means computers do not behave in a random way. 
In order to create a pseudorandom number computers use algorithms called pseudorandom number generators.These numbers appear to be random but arent. The seed serves as the starting input for the random number generator.
For example, I will generate a array of 5 numbers "randomly" generated between 0 and 100 below. The seed below is 0. As long as the seed remains the same, the output will remain the same.


In [6]:
np.random.seed(0)
np.random.randint(100, size = 5)

array([44, 47, 64, 67, 67])

If I do this input again the output will be the same.

In [7]:
np.random.seed(0)
np.random.randint(100, size = 5)

array([44, 47, 64, 67, 67])

The output array was the same. Therefore we can see that it is not truly random.

Numpy seed is used to provide an input to the number generator. It enables the use to provide a seed value to the generator.

This seed then works in partnership with other functions within numpy. Most commonly it works with the numpy.random function. As we saw above there are many numpy random functions that we can use with numpy seed. For example, we can use nump.random.normal together with numpy.random.seed to produce normally distributed numbers. Or numpy.random.randint with numpy.random.seed will produce random integers.

Below I will input the exact same code as above but with a different seed. This will change the output.


In [8]:
np.random.seed(9)
np.random.randint(100, size = 5)

array([92, 54, 56, 22, 65])

The output was different. With a different seed we get a different result.

Numpy.random.seed makes code repeatable. If we don't define a seed when drawing random numbers then the numpy will generate a seed for us. However this would not be reproducable so defining a seed is recomended. We use the seed when we want to make proccesses repeatable. This works well for testing. Seed also facilitates sharing of code. Because it is repeatable it is easy to share. The code will remain repeatable as long as the seed remains the same.



##### References:
https://www.w3schools.com/python/numpy/numpy_intro.asp
https://www.datacamp.com/community/tutorials/numpy-random